### ISSUE TITLE
Error in generating js template bot

### ISSUE THREAD

**Issue by RelativeSure** [Darkempire78/Discord-Tools#11]
![image](https://user-images.githubusercontent.com/67839982/111527040-b730be80-875f-11eb-9fdb-6487e258c61b.png)
![image](https://user-images.githubusercontent.com/67839982/111527184-f101c500-875f-11eb-9ea0-355607e19ce9.png)

I get these errors when trying to generate a template bot.

**Comment by Darkempire78** [comment]
Commands work for me 🤔

**Comment by Darkempire78** [comment]
Have you opened a folder after trying the command ? Because the bot cannot be created if there is no folder where paste the code. I will check this suggestion tomorrow and add a warning message if it's the error

**Comment by Darkempire78** [comment]
Fixed
