### ISSUE TITLE
Error on the discord.py template(OnCommandError.py)

### ISSUE THREAD

**Issue by Thecornsyrup** [Darkempire78/Discord-Tools#13]
The discord.py template has an error on the OnCommandError cog (Well I believe it was a mistake)

`async def on_command_error(self, ctx:commands.Contex, error:commands.CommandError):`
***Contex***

I'm not entirely sure about it, as I'm fairly new to using discord.py as well as ext
but thought it'd be nice to make an issue about it anyway.

**Comment by Darkempire78** [comment]
It's fixed! 
Thank you
