### ISSUE TITLE
djs.cmd / djs.cmd+ generating wrong commands

### ISSUE THREAD

**Issue by KintonHiryuu** [Darkempire78/Discord-Tools#14]
I used the "generate discord-js bot" function.
When i want to create a command, i use "djs.cmd+" (tested with djs.cmd too) then write my code
try to execute the command and.... the bot can't "run" the command

error is : generating a "execute" function instead of a "run" function
+ the placed arguments are wrongly placed, leading the "message" to be the "client" variable

![image](https://user-images.githubusercontent.com/60929021/113526603-f6ae3600-95ba-11eb-9498-5a66147122a3.png)
![image](https://user-images.githubusercontent.com/60929021/113526619-09286f80-95bb-11eb-8820-d68afe23d78e.png)
![image](https://user-images.githubusercontent.com/60929021/113526635-19404f00-95bb-11eb-8b08-95a024bdc5a5.png)

PS : why not add a `const Discord = require("discord.js")` at the beginning so we can use djs.embed more efficiently ?

PS² : thanks a lot for this time-saver tool, i'll try to contribute as soon as i have some time to

**Comment by Darkempire78** [comment]
> PS : why not add a const Discord = require("discord.js") at the beginning so we can use djs.embed more efficiently ?
It can be boring if you have to delete each time this line (if you already have imported it), but we can add a snippets `djs.import` 🤔 @KintonHiryuu

**Comment by Darkempire78** [comment]
>  thanks a lot for this time-saver tool, i'll try to contribute as soon as i have some time to

Thank you too :D

**Comment by Darkempire78** [comment]
It's not a bug. 🎆
You can change it when you generate the code (use tab)
![image](https://user-images.githubusercontent.com/50015928/113844488-d20db600-9794-11eb-88f4-fbf34c8960a2.png)
