### ISSUE TITLE
Should i add aoi.js ?

### ISSUE THREAD

**Issue by Whirl21** [Darkempire78/Discord-Tools#19]
This is going to be a big thing as aoi has a large variety of stuff I would wanna add just  seeking your permission for that

**Comment by Darkempire78** [comment]
Sure @Whirl21 ,
Adding a new wrapper is always welcome!

Can you join the Discord server to discuss it in more detail? 
https://discord.com/invite/sPvJmY7mcV

**Comment by Darkempire78** [comment]
@Whirl21 👀

**Comment by Whirl21** [comment]
man truth be told im all talk but no action 
well recently aoijs has become retarded 
it's shit 
now
tbh i'll convert your djs snippets to v13 someday

**Comment by Darkempire78** [comment]
No problem, so I close the issue

**Comment by Whirl21** [comment]
xD
