### ISSUE TITLE
Listeners

### ISSUE THREAD

**Issue by Akavvi** [Darkempire78/Discord-Tools#2]
Add listeners as a folder and register them in the code

**Comment by Darkempire78** [comment]
In the bot template ?

**Comment by Akavvi** [comment]
> In the bot template ?

Yep, you know, like registering commands, only listeners and the event itself

**Comment by Darkempire78** [comment]
i added all events to Discord.js and Discord.py

**Comment by Darkempire78** [comment]
released!
