### ISSUE TITLE
Harmony Snippets

### ISSUE THREAD

**Issue by Kyrruu** [Darkempire78/Discord-Tools#27]
Salut, j'ai test l'extension parce que ça m'a intéressé mais les snippets Harmony ne fonctionnent pas, en fait bah y'en a tout simplement pas ou bien ils sont pas détectés.

Une idée d'où ça vient ?

**Comment by Kyrruu** [comment]
Oui, mais ça y est j'ai trouvé d'où venait le problème et c'est réglé.

Cependant il y a plusieurs snippets qui font souvent la même chose, je trouve que c'est du poids en plus inutilement pour l'extension.

**Comment by Darkempire78** [comment]
Souvent, il y a un version simplifié des snippets et une version complete, ce qui permet de ne pas passer son temps a rajouter ou supprimer des choses quand on code
