### ISSUE TITLE
Update Discord.js snippets to v14

### ISSUE THREAD

**Issue by R-Rajaneesh** [Darkempire78/Discord-Tools#30]
Discord.js v13 was released quite a long back and has a ton of changes to the typings, hopefully, you can add it

**Comment by Darkempire78** [comment]
Yes, it have to be done, but I'm very busy for the moment...

**Comment by AriaFantom** [comment]
Please add it we are waiting

**Comment by Darkempire78** [comment]
I did not use Discord.js since the v13, help would be welcome

**Comment by AriaFantom** [comment]
What kind of help u want

**Comment by Darkempire78** [comment]
@AriaFantom I'm not able to update the discord.js snippets because I do not use it. So someone should do it for me

**Comment by chethanyadav456** [comment]
@Darkempire78 Sure, I can update the code to the latest version of discord.js, which is v14. I up to now started working on it. 
One suggestion: add this project to hacktoberfest.

Here is how you can add this project to hacktoberfest.
- https://hacktoberfest.com/participation/
- https://dev.to/gkhan205/how-can-i-add-my-project-on-hacktoberfest-to-accept-contributions-2dn0

This helps to update this project up to date.

**Comment by Darkempire78** [comment]
@chethanyadav456 I added it to Hacktoberfest
It would be great to update the discord.js version!

**Comment by chethanyadav456** [comment]
> @chethanyadav456 I added it to Hacktoberfest
> It would be great to update the discord.js version!

Sure 😁

**Comment by chethanyadav456** [comment]
@Darkempire78 Close this issue as it is solved!

**Comment by R-Rajaneesh** [comment]
Thankyou @chethanyadav456, I will close this issue.

Issue Resolved.
