### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Jalkarna** [Darkempire78/Discord-Tools#32]
- Issue Type: `Bug`
- Extension Name: `discord-tools`
- Extension Version: `1.4.3`
- OS Version: `Windows_NT x64 6.3.9600`
- VS Code version: `1.61.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by KintonHiryuu** [comment]
I think windows7 sp2 or later are the only OSes really supported, even doubting if w8.1 isnt the minimal one tbh
