### ISSUE TITLE
Add permission manager

### ISSUE THREAD

**Issue by DynamoYT** [Darkempire78/Discord-Tools#4]
in `index.js` spelling of `type` is wrong

<img width="685" alt="Screenshot_1" src="https://user-images.githubusercontent.com/63182360/103876458-af1e2800-50f9-11eb-8637-1221ff3678d4.png">

**Comment by DynamoYT** [comment]
Suggestion: Add permission.
like
```
module.exports = {
     permissions: ["EMBED_LINKS"]
}
```
If the bot doesn't have the `EMBED_LINKS` permission, it'll show a message in the channel that It required this permission

**Comment by Darkempire78** [comment]
I have fixed this error

**Comment by Darkempire78** [comment]
You can certainly manage permission errors in the error event

**Comment by Darkempire78** [comment]
The new extension version is released! Thanks you.
Do note forget to add a good note to the extension on the marketpalce!
