### ISSUE TITLE
embed "not bound" and on start gives error and says event loop is closed

### ISSUE THREAD

**Issue by JacProsser** [Darkempire78/Discord-Tools#5]
embed "not bound" and on start gives error and says event loop is closed

**Comment by Darkempire78** [comment]
Can you give me more about your issue ?
The context, when, where...

**Comment by JacProsser** [comment]
let me get screenshots from my pc and i'll show you

**Comment by JacProsser** [comment]
![Screenshot_75](https://user-images.githubusercontent.com/48368615/104483318-e55b1c00-55bf-11eb-824d-3657739b87c9.png)
![Screenshot_74](https://user-images.githubusercontent.com/48368615/104483322-e5f3b280-55bf-11eb-955d-8187b38a1c60.png)

**Comment by Darkempire78** [comment]
Do you changed anything in the python template ?

**Comment by Darkempire78** [comment]
Remove the line number 31 in the main.py : ``intents.members = True``
I will update the template

**Comment by JacProsser** [comment]
ah yes it works now thanks
