### ISSUE TITLE
cant use a java template bot generator

### ISSUE THREAD

**Issue by niclan051** [Darkempire78/Discord-Tools#51]
i tried using a "generate jda template bot" feature and got this error message
![error message](https://user-images.githubusercontent.com/96299784/211193752-86821eae-341e-4a69-a9e8-40f0cc25cb4e.png)

**Comment by niclan051** [comment]
i cant generate a discord.js or a discord.py template bot either

**Comment by niclan051** [comment]
turns out none of the commands work for me

**Comment by Darkempire78** [comment]
Try to uninstall the re install

**Comment by niclan051** [comment]
still every command results in this error message

**Comment by chethanyadav456** [comment]
All the templates are working fine. Once update your vs code and extension.
