### ISSUE TITLE
Can't figure out the chat function.

### ISSUE THREAD

**Issue by Exator921** [Darkempire78/Discord-Tools#62]
I'm trying to open the chat for this tool but I can't seem to get it to open as it says "No channel selected". If you or someone else could assist me in making it work that would be great.

**Comment by TechnoLukas** [comment]
I am having same issue :/

**Comment by TechnoLukas** [comment]
@Exator921 I found the solution :)
If you already successfully setted up your Discord token, then you need to execute these commands:
- "Start Discord chat"
- "Open the Discord chat"
- "Focus on discord view" (should pop up in left bottom corner), in that menu you should see your Discord servers, and then click on the chat you want to see.

This should select the channel :)

**Comment by Exator921** [comment]
> @Exator921 I found the solution :) If you already successfully setted up your Discord token, then you need to execute these commands:
> 
> * "Start Discord chat"
> * "Open the Discord chat"
> * "Focus on discord view" (should pop up in left bottom corner), in that menu you should see your Discord servers, and then click on the chat you want to see.
> 
> This should select the channel :)

I figured it out, thank you.
