### ISSUE TITLE
Java Version removed?

### ISSUE THREAD

**Issue by ThatGuyJamal** [Darkempire78/Discord-Tools#7]
Hello, 

I was wondering why the java version of this extension was removed?

**Comment by Darkempire78** [comment]
The java version exists, but there is no template bot (only snippets).

**Comment by ThatGuyJamal** [comment]
Will there ever be a template? 

Thanks for the reply. How do you access the snips?

**Comment by Darkempire78** [comment]
You need to use the `jda.` prefix to use snippets, for example : `jda.embed`
I'm not a very good java developer, but you can propose a bot template to improve the extension!

**Comment by ThatGuyJamal** [comment]
Ah okay, thanks. I only know the basics of java but if I ever get good at java and Discord I will try. I mostly know javascript.
